name: compose-node-nest-graphql
    
services:
  db:
    # pg out container uri     : postgresql://postgres:postgres@localhost:5432/mydb?schema=public
    # pg in container uri      : postgresql://postgres:postgres@db:5432/mydb?schema=public
    container_name: postgres-db-container
    image: postgres:latest
    restart: on-failure:3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - 5432:5432
    volumes:
      - ./tmp/db:/var/lib/postgresql/data