name: compose-node-nest-graphql
    
services:
  db:
    container_name: postgres-db-container
    image: postgres:latest
    restart: on-failure:3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my_db
    ports:
      - 5432:5432
    volumes:
      - ./tmp/db:/var/lib/postgresql/data