
# Build Stage
FROM node:22-alpine3.20 as build_stage

WORKDIR /app

RUN npm i
RUN npm run pre-commit
RUN npm run build:ncc

# Run Stage
FROM node:22-alpine3.20 as run_stage

WORKDIR /app

COPY --from=build_stage /app/dist /dist
COPY --from=build_stage /app/.env /

EXPOSE 3500

CMD [ "node", "./dist/index.js" ]


